

#ifndef PORT_PRIVATE_H_
#define PORT_PRIVATE_H_

#define PORTA_REGISTER *((volatile uint8_t*)(0x3b))
#define DDRA_REGISTER  *((volatile uint8_t*)(0x3A))

#define PORTB_REGISTER *((volatile uint8_t*)(0x38))
#define DDRB_REGISTER  *((volatile uint8_t*)(0x37))

#define PORTC_REGISTER *((volatile uint8_t*)(0x35))
#define DDRC_REGISTER  *((volatile uint8_t*)(0x34))

#define PORTD_REGISTER *((volatile uint8_t*)(0x32))
#define DDRD_REGISTER  *((volatile uint8_t*)(0x31))


/*   Concatination     */
#define CONC(P7,P6,P5,P4,P3,P2,P1,P0)          CONC_HELPER(P7,P6,P5,P4,P3,P2,P1,P0)
#define CONC_HELPER(P7,P6,P5,P4,P3,P2,P1,P0)   0b##P7##P6##P5##P4##P3##P2##P1##P0



#define PORTA_DIR  CONC(PORTA_PIN0_DIR,PORTA_PIN1_DIR,PORTA_PIN2_DIR,PORTA_PIN3_DIR,PORTA_PIN4_DIR,PORTA_PIN5_DIR,PORTA_PIN6_DIR,PORTA_PIN7_DIR)
#define PORTB_DIR  CONC(PORTB_PIN0_DIR,PORTB_PIN1_DIR,PORTB_PIN2_DIR,PORTB_PIN3_DIR,PORTB_PIN4_DIR,PORTB_PIN5_DIR,PORTB_PIN6_DIR,PORTB_PIN7_DIR)
#define PORTC_DIR  CONC(PORTC_PIN0_DIR,PORTC_PIN1_DIR,PORTC_PIN2_DIR,PORTC_PIN3_DIR,PORTC_PIN4_DIR,PORTC_PIN5_DIR,PORTC_PIN6_DIR,PORTC_PIN7_DIR)
#define PORTD_DIR  CONC(PORTD_PIN0_DIR,PORTD_PIN1_DIR,PORTD_PIN2_DIR,PORTD_PIN3_DIR,PORTD_PIN4_DIR,PORTD_PIN5_DIR,PORTD_PIN6_DIR,PORTD_PIN7_DIR)

#define PORTA_INITIAL_VALUE CONC(PORTA_PIN0_INITIAL_VALUE,PORTA_PIN1_INITIAL_VALUE,PORTA_PIN2_INITIAL_VALUE,PORTA_PIN3_INITIAL_VALUE,PORTA_PIN4_INITIAL_VALUE,PORTA_PIN5_INITIAL_VALUE,PORTA_PIN6_INITIAL_VALUE,PORTA_PIN7_INITIAL_VALUE) 
#define PORTB_INITIAL_VALUE CONC(PORTB_PIN0_INITIAL_VALUE,PORTB_PIN1_INITIAL_VALUE,PORTB_PIN2_INITIAL_VALUE,PORTB_PIN3_INITIAL_VALUE,PORTB_PIN4_INITIAL_VALUE,PORTB_PIN5_INITIAL_VALUE,PORTB_PIN6_INITIAL_VALUE,PORTB_PIN7_INITIAL_VALUE) 
#define PORTC_INITIAL_VALUE CONC(PORTC_PIN0_INITIAL_VALUE,PORTC_PIN1_INITIAL_VALUE,PORTC_PIN2_INITIAL_VALUE,PORTC_PIN3_INITIAL_VALUE,PORTC_PIN4_INITIAL_VALUE,PORTC_PIN5_INITIAL_VALUE,PORTC_PIN6_INITIAL_VALUE,PORTC_PIN7_INITIAL_VALUE) 
#define PORTA_INITIAL_VALUE CONC(PORTD_PIN0_INITIAL_VALUE,PORTD_PIN1_INITIAL_VALUE,PORTD_PIN2_INITIAL_VALUE,PORTD_PIN3_INITIAL_VALUE,PORTD_PIN4_INITIAL_VALUE,PORTD_PIN5_INITIAL_VALUE,PORTD_PIN6_INITIAL_VALUE,PORTD_PIN7_INITIAL_VALUE) 

#endif