#include "PORT_interface.h"
#include "PORT_private.h"
#include "PORT_config.h"

void PORT_voidinit (void)
{
	DDRA_REGISTER=PORTA_DIR;
	DDRB_REGISTER=PORTB_DIR;
	DDRC_REGISTER=PORTC_DIR;
	DDRD_REGISTER=PORTD_DIR;
	
	PORTA_REGISTER=PORTA_INITIAL_VALUE;
	PORTB_REGISTER=PORTB_INITIAL_VALUE;
	PORTC_REGISTER=PORTC_INITIAL_VALUE;
	PORTD_REGISTER=PORTD_INITIAL_VALUE;
}
