

#ifndef PORT_CONFIG_H_
#define PORT_CONFIG_H_


#define DIO_INPUT 0
#define DIO_OUTPUT 1

#define INPUT_FLOTING 0
#define INPUT_PULLUP 1

#define OUTPUT_HIGH 1
#define OUTPUT_LOW  0



#define PORTA_PIN0_DIR  DIO_OUTPUT 
#define PORTA_PIN1_DIR  DIO_OUTPUT 
#define PORTA_PIN2_DIR  DIO_OUTPUT 
#define PORTA_PIN3_DIR  DIO_OUTPUT 
#define PORTA_PIN4_DIR  DIO_OUTPUT 
#define PORTA_PIN5_DIR  DIO_OUTPUT 
#define PORTA_PIN6_DIR  DIO_OUTPUT 
#define PORTA_PIN7_DIR  DIO_OUTPUT 


#define PORTB_PIN0_DIR  DIO_OUTPUT 
#define PORTB_PIN1_DIR  DIO_OUTPUT 
#define PORTB_PIN2_DIR  DIO_OUTPUT 
#define PORTB_PIN3_DIR  DIO_OUTPUT 
#define PORTB_PIN4_DIR  DIO_OUTPUT 
#define PORTB_PIN5_DIR  DIO_OUTPUT 
#define PORTB_PIN6_DIR  DIO_OUTPUT 
#define PORTB_PIN7_DIR  DIO_OUTPUT 


#define PORTC_PIN0_DIR  DIO_OUTPUT 
#define PORTC_PIN1_DIR  DIO_OUTPUT 
#define PORTC_PIN2_DIR  DIO_OUTPUT 
#define PORTC_PIN3_DIR  DIO_OUTPUT 
#define PORTC_PIN4_DIR  DIO_OUTPUT 
#define PORTC_PIN5_DIR  DIO_OUTPUT 
#define PORTC_PIN6_DIR  DIO_OUTPUT 
#define PORTC_PIN7_DIR  DIO_OUTPUT 


#define PORTD_PIN0_DIR  DIO_OUTPUT 
#define PORTD_PIN1_DIR  DIO_OUTPUT 
#define PORTD_PIN2_DIR  DIO_OUTPUT 
#define PORTD_PIN3_DIR  DIO_OUTPUT 
#define PORTD_PIN4_DIR  DIO_OUTPUT 
#define PORTD_PIN5_DIR  DIO_OUTPUT 
#define PORTD_PIN6_DIR  DIO_OUTPUT 
#define PORTD_PIN7_DIR  DIO_OUTPUT 


#define PORTA_PIN0_INITIAL_VALUE INPUT_FLOTING
#define PORTA_PIN1_INITIAL_VALUE INPUT_FLOTING
#define PORTA_PIN2_INITIAL_VALUE INPUT_FLOTING
#define PORTA_PIN3_INITIAL_VALUE INPUT_FLOTING
#define PORTA_PIN4_INITIAL_VALUE INPUT_FLOTING
#define PORTA_PIN5_INITIAL_VALUE INPUT_FLOTING
#define PORTA_PIN6_INITIAL_VALUE INPUT_FLOTING
#define PORTA_PIN7_INITIAL_VALUE INPUT_FLOTING

#define PORTB_PIN0_INITIAL_VALUE INPUT_FLOTING
#define PORTB_PIN1_INITIAL_VALUE INPUT_FLOTING
#define PORTB_PIN2_INITIAL_VALUE INPUT_FLOTING
#define PORTB_PIN3_INITIAL_VALUE INPUT_FLOTING
#define PORTB_PIN4_INITIAL_VALUE INPUT_FLOTING
#define PORTB_PIN5_INITIAL_VALUE INPUT_FLOTING
#define PORTB_PIN6_INITIAL_VALUE INPUT_FLOTING
#define PORTB_PIN7_INITIAL_VALUE INPUT_FLOTING

#define PORTC_PIN0_INITIAL_VALUE INPUT_FLOTING
#define PORTC_PIN1_INITIAL_VALUE INPUT_FLOTING
#define PORTC_PIN2_INITIAL_VALUE INPUT_FLOTING
#define PORTC_PIN3_INITIAL_VALUE INPUT_FLOTING
#define PORTC_PIN4_INITIAL_VALUE INPUT_FLOTING
#define PORTC_PIN5_INITIAL_VALUE INPUT_FLOTING
#define PORTC_PIN6_INITIAL_VALUE INPUT_FLOTING
#define PORTC_PIN7_INITIAL_VALUE INPUT_FLOTING

#define PORTD_PIN0_INITIAL_VALUE INPUT_FLOTING
#define PORTD_PIN1_INITIAL_VALUE INPUT_FLOTING
#define PORTD_PIN2_INITIAL_VALUE INPUT_FLOTING
#define PORTD_PIN3_INITIAL_VALUE INPUT_FLOTING
#define PORTD_PIN4_INITIAL_VALUE INPUT_FLOTING
#define PORTD_PIN5_INITIAL_VALUE INPUT_FLOTING
#define PORTD_PIN6_INITIAL_VALUE INPUT_FLOTING
#define PORTD_PIN7_INITIAL_VALUE INPUT_FLOTING

#endif