#ifndef EXTI_CONFIG_H_
#define EXTI_CONFIG_H_


/*SET EXTI_LINE
	- DISABLE 
	- ENABLE

AND SET SENSE CONTROL
  CHOISE FOR INT1 & INT0
	-LOW_LEVEL
	-RISING_EDGE
	-FALLING_EDGE
	-ON_CHANGE
  CHOISE FOR INT2
		-RISING_EDGE
    -FALLING_EDGE
	 */
	
#define EXTI_LINE0  ENABLE 
#define SENSE_CONTROL0 LOW_LEVEL

#define EXTI_LINE1  ENABLE  
#define SENSE_CONTROL1 LOW_LEVEL 

#define EXTI_LINE2  ENABLE  
#define SENSE_CONTROL2 RISING_EDGE 


#endif