
#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_

/*SET SPI MODE
	-SPI_ENABLE
	-SPI_DISABLE
	*/
#define SPI_MODE SPI_ENABLE  
/*set SPI_Interrupt
	-SPI_Interrupt_ENABLE
	-SPI_Interrupt_DISABLE
	*/
#define SPI_Interrupt SPI_Interrupt_ENABLE 

/*SET DATA ORDER 
	-SPI_LSB_FIRIST
	-SPI_MSB_FIRIST
	*/
#define SPI_DATA_ORDER SPI_LSB_FIRIST


/* SELECT MASTER OR SLAVE
	-SPI_MASTER
	-SPI_SLAVE
	*/
#define SPI_MASTER_SLAVE SPI_MASTER


/*SET Clock Polarity  
	-SPI_LEADING_RISING_TRAILING_FALLING
    -SPI_LEADING_FALLING_TRAILING_RISING
    */
#define SPI_Clock_Polarity SPI_LEADING_RISING_TRAILING_FALLING

/*Set Clock Phase 
	-SPI_SAMPLE_LEADING_SETUP_TRAILING
	-SPI_SETUP_LEADING_SAMPLE_TRAILING
 */
#define SPI_CLOCK_PHASE	SPI_SAMPLE_LEADING_SETUP_TRAILING


/*SET SPI_Clock_Rate
	-SPI_FREQ_DIVIDED_BY_2
	-SPI_FREQ_DIVIDED_BY_4
	-SPI_FREQ_DIVIDED_BY_8
	-SPI_FREQ_DIVIDED_BY_16
	-SPI_FREQ_DIVIDED_BY_32
	-SPI_FREQ_DIVIDED_BY_64
	-SPI_FREQ_DIVIDED_BY_128
	*/
#define SPI_Clock_Rate SPI_FREQ_DIVIDED_BY_16


#endif